# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

## Installation Instructions

### NumPy is already included in your environment! You are good to go if you are using the tsa_course env!

_____
##### For those not using the provided environment:

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](https://www.scipy.org/install.html)**

_____

## Using NumPy

Once you've installed NumPy you can import it as a library:

**Numpy Part 1**

In [164]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [165]:
## create numpy array
mylist= [1,2,3]

In [166]:
## type of the list
type(mylist)

list

In [167]:
## to convert existing list to numpy array
np.array(mylist)

array([1, 2, 3])

In [168]:
## assigning a name to numpy array
arr= np.array(mylist)

In [169]:
## display the array
arr

array([1, 2, 3])

In [170]:
## creating 2-D new list
mylist= [[1,2,3],[4,5,6],[7,8,9]]

In [171]:
## display the list
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [172]:
## to convert existing list to numpy array
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
## to convert existing list to numpy array
## assigning a name to numpy array
mymatrix= np.array(mylist)

In [174]:
## to display the matrix
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
## shape of the matrix
mymatrix.shape

(3, 3)

## Built-in Methods

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [178]:
## create a array of range (0,10)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
## create a array of range 0 to 11 and have step size is 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [180]:
## create an array having 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [181]:
## the type of this is float
type(0.)

float

In [182]:
## create an array having 4 by 10 zeros
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [183]:
## create an array having 5 by 5 zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [184]:
## create an array having 5 by 5 zeros
## numpy add 4 to each of the element
np.zeros((5,5))+ 4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [185]:
## create an array having 5 by 5 ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [186]:
## create an array having 5 by 5 ones
## adding 4 to each element
np.ones((5,5))+ 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [187]:
## create an array having 4 ones
## multiplying 100 to each element
np.ones(4)* 100

array([100., 100., 100., 100.])

In [188]:
## create an array having 4 ones
## dividing 100 to each element
np.ones(4)/ 100

array([0.01, 0.01, 0.01, 0.01])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [189]:
## arange is integer having (lower,upper,step)
## linspace is inclusive start and inclusive stop
## give 20 numbers between 0 and 1
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [190]:
## give 5 by 5 2-D array identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Numpy Part 2**

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [191]:
## create one random num b/w 0 and 1
np.random.rand(1)

array([0.68530633])

In [192]:
## create 4 random numbers
np.random.rand(4)

array([0.51786747, 0.04848454, 0.13786924, 0.18696743])

In [193]:
## create 5 by 5 random numbers
np.random.rand(5,5)

array([[0.9943179 , 0.5206654 , 0.57878954, 0.73481906, 0.54196177],
       [0.91315356, 0.80792015, 0.40299783, 0.35722434, 0.95287671],
       [0.34363158, 0.86509982, 0.83027771, 0.53816145, 0.92246937],
       [0.09714648, 0.10284749, 0.7015073 , 0.89047987, 0.1595603 ],
       [0.27557254, 0.67249153, 0.16430312, 0.70137114, 0.48763522]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [194]:
## create one random num
## randn (gives values b/w -1 and 1)
np.random.randn(1)

array([0.23812696])

In [195]:
## create one random num
## (value b/w -1 and 1)
np.random.normal(1)

2.9966522853695663

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [196]:
## create one random integer number b/w 0 and 100
np.random.randint(1,100)

55

In [197]:
## create 10 random integer numbers b/w 1 and 100
np.random.randint(1,100,10)

array([87, 10, 46,  3, 19, 59, 93, 12, 11, 95])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [198]:
## if we wanna get same random numbers use seed command
## i get same 4 random numbers as video lectr 
## but it is important these two lines should be in same cell
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [199]:
## if we don't write in same cell we can't get same numbers
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [200]:
## if we don't write in same cell we can't get same numbers
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [201]:
## creating an array
arr= np.arange(25)

In [202]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [203]:
## creating random array 0f 10 int numbers b/w 0 and 50
ranarr= np.random.randint(0,50,10)

In [204]:
ranarr

array([49, 19, 47,  8, 29, 34, 44,  8, 19, 10])

In [205]:
arr.shape

(25,)

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [206]:
## reshape it to 5 by 5 matrix (2-D array)  
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [212]:
## to display the array
ranarr

array([49, 19, 47,  8, 29, 34, 44,  8, 19, 10])

In [215]:
## display the min value in ranarray
ranarr.min()

8

In [216]:
## display the max value in ranarray
ranarr.max()

49

In [217]:
## display the position of max value in the ranarry
ranarr.argmax()

0

In [218]:
## display the position of min value in the ranarry
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [221]:
ranarr.shape

(10,)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [219]:
ranarr.dtype

dtype('int32')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [241]:
import numpy as np

In [242]:
## Creating sample array
arr = np.arange(0,11)

In [243]:
##Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [244]:
## Get a value at an index
arr[8]

8

In [245]:
## Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [246]:
## Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [247]:
## Get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

In [248]:
## Get values in a range
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [249]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [250]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [251]:
new_arr= arr/2

In [252]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [253]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [254]:
## squaring
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [255]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [256]:
## Setting a value with index range (Broadcasting)
## slicing
arr[0:5]=100

In [257]:
## Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [259]:
## Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

In [261]:
## Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [262]:
## Important notes on Slices
slice_of_arr = arr[0:6]

In [263]:
## Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [265]:
## Change Slice
slice_of_arr[:]=99

In [266]:

## Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [269]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [272]:
## if we did'nt want to effect the original array 
## To get a copy, need to be explicit
arr_copy = arr.copy()

In [274]:
## assigning new value to all elements in arr_copy 
arr_copy[:]= 20

In [275]:
## original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [276]:
## display the array copy
arr_copy

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [277]:
## creating 2_D array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [278]:
## Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [279]:
## Shape
arr_2d.shape

(3, 3)

In [280]:
## Indexing row
## 2nd row
arr_2d[1]

array([20, 25, 30])

In [281]:
## Format is arr_2d[row][col] or arr_2d[row,col]
## Getting individual element value
arr_2d[1][0]

20

In [282]:
## Getting individual element value
arr_2d[1,0]

20

In [283]:
## display the num 45
arr_2d[2,2]

45

In [284]:
## 2D array slicing
## Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [285]:
## Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [286]:
## Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size.

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [287]:
## creating an array and display
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [288]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [289]:
bool_arr = arr>4

In [290]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [292]:
## filter or mask
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [293]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [294]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

In [298]:
import numpy as np

In [299]:
## creating array
arr = np.arange(0,10)

In [300]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [301]:
## adding
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [302]:
## substracting
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [303]:
## multiplying
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [304]:
## This will raise a Warning on division by zero, but not an error!
## It just fills the spot with nan
arr/arr

C:\Users\abdul\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [305]:
## Also a warning (but not an error) relating to infinity
1/arr

C:\Users\abdul\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [306]:
## power 3
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [307]:
## Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [308]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [309]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [310]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\abdul\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [311]:
## creating an array
arr = np.arange(0,10)

In [312]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [313]:
## total sum
arr.sum()

45

In [314]:
## mean of array (45/10=4.5)
arr.mean()

4.5

In [315]:
## max value in an array
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [316]:
## creating an 2_D array
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [317]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [320]:
## sum of the all the elements
arr_2d.sum()

78

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

This tells us that <tt>arr_2d</tt> has 3 rows and 4 columns.

In <tt>arr_2d.sum(axis=0)</tt> above, the first element in each row was summed, then the second element, and so forth.

So what should <tt>arr_2d.sum(axis=1)</tt> return?

In [329]:
## sum along vertical axis
## sum across the rows
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [330]:
## sum along horizental axis
## sum across the columns
arr_2d.sum(axis=1)

array([10, 26, 42])

In [331]:
arr_2d.shape

(3, 4)

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [332]:
import numpy as np

#### 2. Create an array of 10 zeros

In [333]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [334]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [337]:
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [338]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [339]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [342]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [343]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [350]:
np.random.rand(1)

array([0.9943179])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [353]:
np.random.randn(25)

array([ 2.82337430e-02,  3.92746078e-01, -1.44169525e+00,  3.22839962e-04,
       -1.04991168e+00, -2.29937498e-01, -1.28359884e+00, -2.71119174e+00,
       -1.52241044e+00, -1.41620705e+00,  1.10854366e+00,  1.13102858e+00,
        4.98600308e-01,  1.17902193e+00,  1.32268437e+00,  1.85215451e+00,
       -8.92171982e-01,  6.16860709e-01, -1.12182200e+00,  1.65207044e+00,
        1.96925271e-01,  1.03214194e-01, -1.47370259e-01,  1.13128366e+00,
        1.08583909e+00])

#### 11. Create the following matrix:
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [355]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [356]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [357]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [359]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.
20

In [361]:
mat[3,4]

20

#### 15. Write code that reproduces the output shown below.
array([[ 2],
       [ 7],
       [12]])

In [363]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that reproduces the output shown below.
array([21, 22, 23, 24, 25])

In [364]:
mat[4:]

array([[21, 22, 23, 24, 25]])

#### 17. Write code that reproduces the output shown below.
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [365]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Get the sum of all the values in mat
325

In [366]:
mat.sum()

325

#### 19. Get the standard deviation of the values in mat
7.211102550927978

In [371]:
mat.std()

7.211102550927978

#### 20. Get the sum of all the columns in mat
array([55, 60, 65, 70, 75])

In [373]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])